name: "Feature request"
description: "Reports regarding bug, slow performance, memory issues, installation issues"

title: ""
labels: ["enhancement", "documentation"]

body:
  - type: markdown
    attributes:
      value: Always welcome, this is developed by a community of volunteers :)

  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: Please provide the summary.
    validations:
      required: true

  - type: textarea
    id: solutions
    attributes:
      label: Solutions
      placeholder: Solutions, if available.

  - type: textarea
    id: deprecations
    attributes:
      label: APIs to be deprecated
      placeholder: APIs to be deprecated, if the new feature replaces their functionalities.

  - type: textarea
    id: comment
    attributes:
      label: Additional Context
      placeholder: Additional Context to fix the bug, including useful references.
