name: "Revise development workflow"
description: "This may update ./.github directory, ./pyproject.toml etc."

title: "[Dev] "
labels: ["development"]

body:
  - type: markdown
    attributes:
      value: Always welcome, this is developed by a community of volunteers :)

  - type: textarea
    id: problem
    attributes:
      label: Issues of the current workflow
      placeholder: What is the problem?
    validations:
      required: true

  - type: textarea
    id: action
    attributes:
      label: Action items
      placeholder: Action items to solve this issue.

  - type: textarea
    id: comment
    attributes:
      label: Additional Context
      placeholder: Additional Context to fix the bug, including useful references.
